/*
 * MosaicDesigner.java
 *
 * Created on January 25, 2008, 6:12 PM
 */
package net.bcharris.photomosaic.swing;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author  brian
 */
public class MosaicDesigner extends javax.swing.JFrame
{
	private static final transient Log log = LogFactory.getLog(MosaicDesigner.class);

	/** Creates new form MosaicDesigner */
	public MosaicDesigner()
	{
		// Auto-generate GUI init
		initComponents();

		// Center on the screen.
		setLocationRelativeTo(null);

		// Grow to a decent size
		setSize(450, 400);
	}

	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new MosaicDesigner().setVisible(true);
			}
		});
	}

	private void resetTargetImage()
	{
		//Create a file chooser
		final JFileChooser fc = new JFileChooser();
		fc.setMultiSelectionEnabled(false);

		//In response to a button click:
		int returnVal = fc.showOpenDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION)
		{
			File f = fc.getSelectedFile();

			final BufferedImage newTargetImg;
			try
			{
				newTargetImg = ImageIO.read(f);
				if (newTargetImg == null)
				{
					throw new IllegalStateException(String.format("User-selected image file is a non-image '%s'", f.getAbsolutePath()));
				}

				imageGridPanel.setImage(newTargetImg);
			}
			catch (Throwable t)
			{
				log.warn("When loading user-selected image", t);
				return;
			}

			SwingUtilities.invokeLater(new Runnable()
			{
				public void run()
				{
					repaint();
				}
			});
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reqPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imageGridPanel = new net.bcharris.photomosaic.swing.ImageGridPanel();
        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        setTargetImageButton = new javax.swing.JButton();
        controlPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sourceImageRatioTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        finalMosaicWidthTextField = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        sourceImageWidthSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reqPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
        reqPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        jLabel1.setText("# Required Source Images = ?");
        reqPanel.add(jLabel1);

        jLabel3.setText("Final Mosaic Height = ?");
        reqPanel.add(jLabel3);

        getContentPane().add(reqPanel, java.awt.BorderLayout.NORTH);
        getContentPane().add(imageGridPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        setTargetImageButton.setText("Set Target Image");
        setTargetImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTargetImageButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(setTargetImageButton);

        jPanel1.add(buttonPanel);

        controlPanel.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Source image dimension ratio:");
        jLabel2.setToolTipText("Width to height ratio used to crop source images.");
        jLabel2.setAlignmentX(0.5F);
        controlPanel.add(jLabel2);

        sourceImageRatioTextField.setColumns(4);
        sourceImageRatioTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.#########"))));
        sourceImageRatioTextField.setText("1.3333333");
        sourceImageRatioTextField.setToolTipText("Width to height ratio used to crop source images.");
        controlPanel.add(sourceImageRatioTextField);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Final Mosaic Width (px):");
        jLabel5.setAlignmentX(0.5F);
        controlPanel.add(jLabel5);
        jLabel5.getAccessibleContext().setAccessibleName("Image Size");

        finalMosaicWidthTextField.setColumns(4);
        finalMosaicWidthTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        finalMosaicWidthTextField.setText("1600");
        finalMosaicWidthTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                finalMosaicWidthTextFieldFocusLost(evt);
            }
        });
        controlPanel.add(finalMosaicWidthTextField);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Source Image Width (px):");
        jLabel6.setAlignmentX(0.5F);
        controlPanel.add(jLabel6);

        sourceImageWidthSlider.setFont(new java.awt.Font("Tahoma", 0, 12));
        sourceImageWidthSlider.setMajorTickSpacing(400);
        sourceImageWidthSlider.setMaximum(1600);
        sourceImageWidthSlider.setPaintLabels(true);
        controlPanel.add(sourceImageWidthSlider);

        jPanel1.add(controlPanel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	private void setTargetImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTargetImageButtonActionPerformed
		resetTargetImage();
}//GEN-LAST:event_setTargetImageButtonActionPerformed

	private void finalMosaicWidthTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finalMosaicWidthTextFieldFocusLost
		
	}//GEN-LAST:event_finalMosaicWidthTextFieldFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JFormattedTextField finalMosaicWidthTextField;
    private net.bcharris.photomosaic.swing.ImageGridPanel imageGridPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel reqPanel;
    private javax.swing.JButton setTargetImageButton;
    private javax.swing.JFormattedTextField sourceImageRatioTextField;
    private javax.swing.JSlider sourceImageWidthSlider;
    // End of variables declaration//GEN-END:variables
}
