/*
 * SetPrioritiesDialog.java
 *
 * Created on January 26, 2008, 1:08 PM
 */
package net.bcharris.photomosaic.swing;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author  brian
 */
public class SetPrioritiesDialog extends javax.swing.JDialog
{
	private final ImageGridPanel imageGridPanel;
	private final MouseAdapter mouseHandler;
	
	/** Creates new form SetPrioritiesDialog */
	public SetPrioritiesDialog(Frame owner, ImageGridPanel imageGridPanel)
	{
		super(owner, "Set Section Priorities");
		
		this.imageGridPanel = imageGridPanel;
		initComponents();
		this.mouseHandler = new MouseAdapter()
		{
			@Override
			public void mouseClicked(MouseEvent e)
			{
				changePriority(e.getPoint());
			}
			
			@Override
			public void mouseDragged(MouseEvent e)
			{
				changePriority(e.getPoint());
			}
		};
		this.imageGridPanel.addMouseListener(mouseHandler);
		this.imageGridPanel.addMouseMotionListener(mouseHandler);
		add(imageGridPanel, BorderLayout.CENTER);
	}
	
	// Not necessary
//	@Override
//	protected void processWindowEvent(WindowEvent e)
//	{
//		super.processWindowEvent(e);
//		if (e.getID() == WindowEvent.WINDOW_CLOSING)
//		{
//			// Clean up when we're done.
//			removeMouseListener(mouseHandler);
//			removeMouseMotionListener(mouseHandler);
//		}
//	}
	
	private void changePriority(Point p)
	{
		Point cell = imageGridPanel.getCellForPoint(p);
		
		// Outside of image
		if (cell == null)
		{
			return;
		}
		
		imageGridPanel.removePriority(cell);
		if (addToFrontButton.isSelected())
		{
			imageGridPanel.addPriority(0, cell);
		}
		else if (addToEndButton.isSelected())
		{
			imageGridPanel.addPriority(cell);
		}
		else if (addCustomButton.isSelected())
		{
			String input = JOptionPane.showInputDialog(this, "What priority? (>= 1)");
			try
			{
				int pos = Integer.parseInt(input) - 1;
				if (pos >= 0)
				{
					imageGridPanel.addPriority(pos, cell);
				}
			}
			catch (NumberFormatException e)
			{
				// Bah
				return;
			}
		}
		
		SwingUtilities.invokeLater(new Runnable()
		{
			public void run()
			{
				imageGridPanel.repaint();
			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        startOverButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addToFrontButton = new javax.swing.JRadioButton();
        addToEndButton = new javax.swing.JRadioButton();
        addCustomButton = new javax.swing.JRadioButton();

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose the priorities of the mosaic sections.");
        jLabel1.setAlignmentX(0.5F);
        jPanel3.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Just click, or click and hold then drag.");
        jLabel2.setAlignmentX(0.5F);
        jPanel3.add(jLabel2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        startOverButton.setText("Start Over");
        startOverButton.setAlignmentX(0.5F);
        startOverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startOverButtonActionPerformed(evt);
            }
        });
        jPanel4.add(startOverButton);

        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        jPanel4.add(doneButton);

        jPanel1.add(jPanel4);

        buttonGroup1.add(addToFrontButton);
        addToFrontButton.setText("Add to front");
        jPanel2.add(addToFrontButton);

        buttonGroup1.add(addToEndButton);
        addToEndButton.setSelected(true);
        addToEndButton.setText("Add to end");
        jPanel2.add(addToEndButton);

        buttonGroup1.add(addCustomButton);
        addCustomButton.setText("Add custom");
        jPanel2.add(addCustomButton);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void startOverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startOverButtonActionPerformed
		this.imageGridPanel.clearPriorities();
		
		SwingUtilities.invokeLater(new Runnable()
		{
			public void run()
			{
				imageGridPanel.repaint();
			}
		});
	}//GEN-LAST:event_startOverButtonActionPerformed

	private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
		setVisible(false);
	}//GEN-LAST:event_doneButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addCustomButton;
    private javax.swing.JRadioButton addToEndButton;
    private javax.swing.JRadioButton addToFrontButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton startOverButton;
    // End of variables declaration//GEN-END:variables
}
